version: '2'

services:
  web:
    build: .
    image: pika-tornado-leak
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/project
    depends_on:
      - rmq

  rmq:
    image: rabbitmq:3.5.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rmq-data:/var/lib/rabbitmq
    hostname: rmq

volumes:
  rmq-data:
    driver: local